-- Run this in the Supabase SQL Editor to create the pass_at_k_runs table.
-- Then you can save and retrieve pass@k run outputs (full model output, generated code,
-- canonical solution, task prompt, metrics, attempts) from the Results page.

create table if not exists pass_at_k_runs (
  id bigint generated by default as identity primary key,
  run_id text unique not null,
  timestamp timestamptz not null default now(),
  model text,
  task_id text,
  task_prompt text,
  canonical_solution text,
  use_humaneval boolean,
  rag_enabled boolean,
  pass_1 integer,
  pass_k double precision,
  k integer,
  n_attempts integer,
  c_passed integer,
  attempts jsonb,
  raw_output text,
  extracted_code text,
  metrics jsonb,
  similarity_score double precision
);

-- Optional: index for filtering by model and timestamp (faster Results page)
create index if not exists idx_pass_at_k_runs_timestamp on pass_at_k_runs (timestamp desc);
create index if not exists idx_pass_at_k_runs_model on pass_at_k_runs (model);

-- Enable RLS if you use it (adjust policy as needed for your project)
-- alter table pass_at_k_runs enable row level security;
